name: scoreboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^4.2.0
  window_manager: ^0.3.8
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: it
  arb_dir: lib/l10n
  output_dir: lib/generated
